### ISSUE TITLE
Cover router: capacity endpoint 500 error

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/cover-router#106]
```
20|cover-r | 2024-07-03 08:23:25.540 +00:00: TypeError: Cannot read properties of undefined (reading 'mul')
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at /home/ubuntu/cover-router/src/lib/capacityEngine.js:142:38
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at Array.map (<anonymous>)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at capacityEngine (/home/ubuntu/cover-router/src/lib/capacityEngine.js:140:52)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at /home/ubuntu/cover-router/src/routes/capacity.js:183:24
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at /home/ubuntu/cover-router/src/lib/helpers.js:13:3
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at Layer.handle [as handle_request] (/home/ubuntu/cover-router/node_modules/express/lib/router/layer.js:95:5)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at next (/home/ubuntu/cover-router/node_modules/express/lib/router/route.js:149:13)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at Route.dispatch (/home/ubuntu/cover-router/node_modules/express/lib/router/route.js:119:3)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at Layer.handle [as handle_request] (/home/ubuntu/cover-router/node_modules/express/lib/router/layer.js:95:5)
20|cover-r | 2024-07-03 08:23:25.540 +00:00:     at /home/ubuntu/cover-router/node_modules/express/lib/router/index.js:284:15
```

**Comment by roxdanila** [comment]
https://v2.nexusmutual.io/cover/product/193 - max period
